// The 33 award categories from the KTA Awards Proposal (Abila Communications, Oct 2026).
// `id` must never change once voting starts: votes and jury scores are stored against it.
// The first 17 ids match the ones created from the earlier deck, so existing data keeps working.
export const CATEGORIES = [
  // Education (focus area, 9)
  { id: "educator-of-the-year", pillar: "Education", name: "Educator of the Year",
    qualifies: "Kenyan teacher or lecturer teaching in a Tanzanian school or college, with at least 3 years in service.",
    evidence: "Learner outcomes, mentorship record, two professional references." },
  { id: "higher-education-leadership", pillar: "Education", name: "Higher Education Leadership",
    qualifies: "Kenyan vice-chancellor, dean, head of department or academic leader at a Tanzanian university or college.",
    evidence: "Programmes launched, enrolment or research growth, institutional impact." },
  { id: "school-leadership-institutional-management", pillar: "Education", name: "School Leadership & Institutional Management",
    qualifies: "Kenyan school principals, headteachers and directors managing top-performing institutions in Tanzania.",
    evidence: "Exam results, inspection or accreditation reports, enrolment trends, governance record." },
  { id: "stem-vocational-education-tvet-excellence", pillar: "Education", name: "STEM & Vocational Education (TVET) Excellence",
    qualifies: "Outstanding educators in science, technology, engineering, mathematics and technical or hands-on skills training.",
    evidence: "Graduate outcomes, employer partnerships, workshop or lab innovations." },
  { id: "early-childhood-development-ecd-pioneer", pillar: "Education", name: "Early Childhood Development (ECD) Pioneer",
    qualifies: "Teachers, tutors and founders excelling in early childhood care, pre-school education and foundational learning.",
    evidence: "Child development progress, licensing, parent testimonials, teaching methods." },
  { id: "edtech-innovation", pillar: "Education", name: "EdTech Innovation",
    qualifies: "Founder or team deploying digital learning tools in Tanzanian classrooms or training settings.",
    evidence: "Users reached, learning-impact data, product demo or portfolio." },
  { id: "research-scholarly-publication-award", pillar: "Education", name: "Research & Scholarly Publication Award",
    qualifies: "University academics and researchers whose published work contributes to policy, regional integration or cross-border development.",
    evidence: "Publication list, citations or policy uptake, institutional reference." },
  { id: "student-mentorship-youth-guidance-award", pillar: "Education", name: "Student Mentorship & Youth Guidance Award",
    qualifies: "Teachers and counsellors who go beyond the curriculum with career counselling, sports coaching and youth leadership training.",
    evidence: "Mentee outcomes, programme descriptions, student and parent testimonials." },
  { id: "community-inclusion", pillar: "Education", name: "Community Inclusion",
    qualifies: "Individual or organisation widening access for girls, learners with disabilities or rural communities.",
    evidence: "Beneficiary numbers, partnerships, community testimonials." },

  // Corporate & Formal (10)
  { id: "executive-leaders", pillar: "Corporate & Formal", name: "Executive Leaders",
    qualifies: "Kenyan CEO, MD or C-suite leader of a company operating in Tanzania for 3+ years.",
    evidence: "Revenue or jobs growth, governance record, leadership references." },
  { id: "healthcare", pillar: "Corporate & Formal", name: "Healthcare",
    qualifies: "Clinicians, administrators and health-enterprise leaders serving Tanzanian patients.",
    evidence: "Licences, patient-outcome or service improvements, peer references." },
  { id: "finance-banking", pillar: "Corporate & Formal", name: "Finance & Banking",
    qualifies: "Bankers, fintech, insurance and investment professionals active in Tanzania.",
    evidence: "Products launched, financial-inclusion reach, portfolio or market growth." },
  { id: "legal-governance-luminaries", pillar: "Corporate & Formal", name: "Legal & Governance Luminaries",
    qualifies: "Licensed advocates, compliance officers and board leaders practising in Tanzania.",
    evidence: "Admission or licence proof, notable matters, ethics and standing record." },
  { id: "engineering-energy-infrastructure-leader", pillar: "Corporate & Formal", name: "Engineering, Energy & Infrastructure Leader",
    qualifies: "Civil engineers, project directors and energy specialists leading major infrastructure, construction and power projects.",
    evidence: "Project scale and delivery record, safety and compliance, professional registration." },
  { id: "telecoms-technology-executive", pillar: "Corporate & Formal", name: "Telecoms & Technology Executive",
    qualifies: "Technology heads, software architects and digital transformation leaders driving enterprise IT and mobile financial services.",
    evidence: "Systems delivered, users or transactions served, innovation case study." },
  { id: "human-capital-organizational-culture-champion", pillar: "Corporate & Formal", name: "Human Capital & Organizational Culture Champion",
    qualifies: "HR directors and talent strategists excelling in workforce development, labour compliance and cross-border team integration.",
    evidence: "Training and retention results, compliance record, team-integration initiatives." },
  { id: "supply-chain-procurement-professional-of-the-year", pillar: "Corporate & Formal", name: "Supply Chain & Procurement Professional of the Year",
    qualifies: "Logistics directors, procurement heads and supply chain managers optimising regional trade corridors.",
    evidence: "Cost or lead-time savings, corridor performance, procurement integrity record." },
  { id: "insurance-risk-actuarial-excellence", pillar: "Corporate & Formal", name: "Insurance, Risk & Actuarial Excellence",
    qualifies: "Leaders in underwriting, risk management and insurance services navigating complex commercial environments.",
    evidence: "Portfolio performance, risk or claims outcomes, professional qualifications." },
  { id: "corporate-sustainability-esg-leader", pillar: "Corporate & Formal", name: "Corporate Sustainability & ESG Leader",
    qualifies: "Corporate managers driving environmental, social and governance initiatives within multinational or regional firms in Tanzania.",
    evidence: "ESG programme results, reporting or certifications, community impact." },

  // Agriculture (2)
  { id: "agri-industrialist-of-the-year", pillar: "Agriculture", name: "Agri-Industrialist of the Year",
    qualifies: "Kenyan-led farming, agro-processing or agri-value-chain business operating in Tanzania.",
    evidence: "Yield or processing volumes, export reach, jobs and out-grower impact." },
  { id: "sustainable-climate-champions", pillar: "Agriculture", name: "Sustainable & Climate Champions",
    qualifies: "Individuals or firms leading renewable energy, conservation or climate-smart initiatives.",
    evidence: "Measurable emissions, ecosystem or resource-saving results, project reports." },

  // Non-Formal & SME (8)
  { id: "micro-enterprise-innovation", pillar: "Non-Formal & SME", name: "Micro-Enterprise Innovation",
    qualifies: "Small or informal Kenyan business with 1+ year trading and a creative solution.",
    evidence: "Revenue growth, customer base, photos or product samples." },
  { id: "hospitality", pillar: "Non-Formal & SME", name: "Hospitality",
    qualifies: "Hotels, restaurants and tourism operators run by Kenyans in Tanzania.",
    evidence: "Service standards, guest ratings, local employment figures." },
  { id: "manufacturing-logistics", pillar: "Non-Formal & SME", name: "Manufacturing & Logistics",
    qualifies: "Factories, assembly, freight and supply-chain operators serving regional trade.",
    evidence: "Output, efficiency gains, cross-border trade volumes." },
  { id: "cross-border-trade-merchant-award", pillar: "Non-Formal & SME", name: "Cross-Border Trade & Merchant Award",
    qualifies: "Small-to-medium traders and merchants who move goods, agricultural produce or services between Kenya and Tanzania.",
    evidence: "Trade records or invoices, years trading, licences, supplier or customer references." },
  { id: "women-led-sme-female-entrepreneur-of-the-year", pillar: "Non-Formal & SME", name: "Women-Led SME / Female Entrepreneur of the Year",
    qualifies: "Women founding or running small businesses, retail shops or informal trade enterprises across Tanzania.",
    evidence: "Revenue or customer growth, jobs created, photos, references." },
  { id: "tech-enabled-sme-digital-retail-award", pillar: "Non-Formal & SME", name: "Tech-Enabled SME / Digital Retail Award",
    qualifies: "Small business owners using e-commerce, social selling (WhatsApp, Instagram) or digital payments to grow their customer base.",
    evidence: "Online sales or customer growth, platform screenshots, payment data." },
  { id: "youth-sme-founder-award", pillar: "Non-Formal & SME", name: "Youth SME Founder Award",
    qualifies: "Young entrepreneurs under 35 building viable micro-businesses, agencies or startups in the region.",
    evidence: "Proof of age, business registration, traction metrics, portfolio." },
  { id: "culinary-food-services-sme-award", pillar: "Non-Formal & SME", name: "Culinary & Food Services SME Award",
    qualifies: "Kenyan-owned restaurants, caterers and food vendors introducing Kenyan cuisine and hospitality to Tanzania.",
    evidence: "Menu and customer reviews, food-safety licences, sales growth." },

  // Impact & Special (4)
  { id: "diaspora-champions", pillar: "Impact & Special", name: "Diaspora Champions",
    qualifies: "Kenyans in Tanzania who mentor, volunteer or lead community programmes.",
    evidence: "Programme reach, volunteer hours, community references." },
  { id: "media-pioneers", pillar: "Impact & Special", name: "Media Pioneers",
    qualifies: "Journalists, broadcasters and digital creators covering East African stories.",
    evidence: "Body of work, audience reach, ethical standards record." },
  { id: "sports-icons", pillar: "Impact & Special", name: "Sports Icons",
    qualifies: "Athletes, coaches and administrators advancing sport in Tanzania.",
    evidence: "Achievements, youth-development work, endorsements." },
  { id: "lifetime-legacy-award-25-years-impact", pillar: "Impact & Special", name: "Lifetime Legacy Award",
    qualifies: "Kenyans with 25+ years of sustained impact in Tanzania, nominated by peers or institutions.",
    evidence: "Career summary, impact evidence, three referees." },
];
